import type { Metadata } from "next";
import { ChakraUiProviders } from "./components/contexts/chakraUiProviders";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "./components/topBar/topBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraUiProviders>
          <TopBar />
          {children}
        </ChakraUiProviders>
      </body>
    </html>
  );
}
